;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        electric-newline-and-maybe-indent
        forward-sexp
        iy-go-to-char--command
        kill-sexp
        org-beginning-of-line
        org-self-insert-command
        sp-backward-barf-sexp
        sp-backward-up-sexp
        sp-beginning-of-sexp
        sp-down-sexp
        sp-rewrap-sexp
        sp-up-sexp
        transpose-sexps
        whole-line-or-region-kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        ))
