;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        forward-sexp
        kill-sexp
        org-self-insert-command
        sp-down-sexp
        sp-end-of-sexp
        sp-forward-slurp-sexp
        sp-unwrap-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
