#+TITLE: Emacs Config
#+STARTUP: overview
#+PROPERTY: header-args:elisp :results silent :tangle init.el
#+AUTO_TANGLE: t
* Table of contents :TOC_3:
:PROPERTIES:
:VISIBILITY: showall
:END:
- [[#notes][Notes]]
  - [[#dependencies][Dependencies]]
    - [[#install-iosevka-comfy-font][Install Iosevka Comfy font]]
    - [[#install-mpv-to-play-media-via-emms][Install mpv to play media via EMMS]]
    - [[#install-ledger][Install ledger]]
    - [[#set-up-gptel][Set up GPTel]]
    - [[#set-up-vterm][Set up Vterm]]
    - [[#set-up-copilot][Set up Copilot]]
    - [[#set-up-jinx][Set up Jinx]]
    - [[#set-up-ripgrep][Set up Ripgrep]]
    - [[#eglot-metals][Eglot: Metals]]
    - [[#anki][Anki]]
    - [[#notdeft][Notdeft]]
- [[#setup][Setup]]
  - [[#load-local-config][Load local config]]
  - [[#os-helpers][OS helpers]]
  - [[#add-lisp-dir-to-load-path][Add 'lisp' dir to load path]]
  - [[#windows-add-git-to-path][Windows: Add Git to path]]
  - [[#straight][Straight]]
  - [[#macos-exec-path-from-shell][MacOS: Exec path from shell]]
- [[#packages][Packages]]
  - [[#emacs][Emacs]]
    - [[#my-emacs][My Emacs]]
  - [[#modus-themes][Modus Themes]]
  - [[#iosevka-comfy-font][Iosevka Comfy font]]
  - [[#dired][Dired]]
    - [[#dired-interactive-functions][Dired interactive functions]]
    - [[#configure-dired][Configure Dired]]
  - [[#project][Project]]
    - [[#my-project][My project]]
  - [[#super-save][Super Save]]
  - [[#emms][EMMS]]
  - [[#ace-window][Ace Window]]
  - [[#vertico][Vertico]]
  - [[#savehist][Savehist]]
  - [[#orderless][Orderless]]
  - [[#consult][Consult]]
    - [[#my-consult][My Consult]]
  - [[#corfu][Corfu]]
  - [[#company][Company]]
  - [[#smartparens][Smartparens]]
  - [[#yasnippet][Yasnippet]]
  - [[#avy][Avy]]
    - [[#my-avy-embark][My Avy-Embark]]
  - [[#link-hint][Link hint]]
  - [[#crux][Crux]]
  - [[#whole-line-or-region][Whole Line or Region]]
  - [[#multiple-cursors][Multiple Cursors]]
  - [[#expand-region][Expand Region]]
  - [[#go-to-char][Go to Char]]
  - [[#magit][Magit]]
  - [[#org-mode][Org mode]]
    - [[#setup-helpers][Setup helpers]]
    - [[#helpers][Helpers]]
    - [[#org-files][Org files]]
    - [[#capturing][Capturing]]
    - [[#agendas][Agendas]]
    - [[#configure][Configure]]
    - [[#org-modern][Org Modern]]
    - [[#auto-tangle][Auto-tangle]]
    - [[#toc][TOC]]
    - [[#restclient][Restclient]]
    - [[#ox-slack][ox-slack]]
  - [[#org-super-links][Org super links]]
  - [[#gptel][GPTel]]
    - [[#my-gptel][My GPTel]]
  - [[#ledger][Ledger]]
    - [[#my-ledger][My Ledger]]
  - [[#vterm][Vterm]]
  - [[#shell][Shell]]
  - [[#copilot][Copilot]]
    - [[#my-copilot][My Copilot]]
  - [[#jinx][Jinx]]
  - [[#ripgrep][Ripgrep]]
  - [[#tree-sitter][Tree Sitter]]
  - [[#eglot][Eglot]]
  - [[#lsp][LSP]]
  - [[#consult-lsp][Consult-LSP]]
  - [[#flycheck][Flycheck]]
  - [[#scala-ts-mode][Scala TS mode]]
  - [[#jarchive][Jarchive]]
  - [[#kubel][Kubel]]
  - [[#markdown][Markdown]]
  - [[#anki-editor][Anki editor]]
  - [[#plantuml][PlantUML]]
  - [[#clojure-mode][Clojure mode]]
  - [[#cider][CIDER]]
  - [[#clerk][Clerk]]
  - [[#openai-tools][OpenAI tools]]
  - [[#terraform][Terraform]]
  - [[#graphql][GraphQL]]
  - [[#decide-mode][decide-mode]]
  - [[#embark][Embark]]
  - [[#emabrk-consult][Emabrk-Consult]]
  - [[#org-roam][Org-roam]]
  - [[#org-roam-ui][Org-roam UI]]
  - [[#notdeft-1][Notdeft]]
  - [[#dash][dash]]
  - [[#envrc][envrc]]
  - [[#emacs-pet][emacs-pet]]
  - [[#just][just]]

* Notes
** Dependencies
*** Install Iosevka Comfy font
**** Fedora
#+begin_src shell
  git clone --depth 1 https://git.sr.ht/~protesilaos/iosevka-comfy ~/tmp/iosevka-comfy
  mkdir ~/.local/share/fonts
  cp -R ~/tmp/iosevka-comfy/iosevka-comfy-fixed ~/.local/share/fonts/
#+end_src

*** Install mpv to play media via EMMS
**** Fedora
#+begin_src shell
  sudo dnf install mpv -y
#+end_src

*** Install ledger
**** Fedora
#+begin_src shell
  sudo dnf install ledger -y
#+end_src

*** Set up GPTel
1) Create a new [[https://platform.openai.com/api-keys][API key]].
2) Add an entry to =~/.authinfo=:
   #+begin_example
     machine api.openai.com login apikey password TOKEN
   #+end_example

*** Set up Vterm
**** Fedora
***** Install fish
#+BEGIN_SRC shell
  sudo dnf install fish -y
#+END_SRC

****** Change shell
#+BEGIN_SRC shell
  chsh
#+END_SRC

After entering the password, enter the path to fish - =/usr/bin/fish=.

Log out and back in to make this effective.

***** Install dependencies for compilation
#+BEGIN_SRC shell
  sudo dnf install cmake libtool -y
#+END_SRC

**** All systems
Configure fish to work w/ vterm as described in https://github.com/akermu/emacs-libvterm?tab=readme-ov-file#shell-side-configuration.

*** Set up Copilot
**** Install Node.js
***** Fedora
#+BEGIN_SRC shell
  sudo dnf install nodejs -y
#+END_SRC
**** Install Copilot server
=M-x copilot-install-server=
**** Login to Copilot
=M-x copilot-login=

*** Set up Jinx
Jinx requires =libenchant=.

On Fedora, install =enchant2-devel=, =pkgconf=. Additional languages are
available as =hunspell-*= packages, e.g. =hunspell-ru=.

*** Set up Ripgrep
On Fedora, install =ripgrep= package.

*** Eglot: Metals
#+BEGIN_SRC shell
  coursier bootstrap \
    --java-opt -XX:+UseG1GC \
    --java-opt -XX:+UseStringDeduplication  \
    --java-opt -Xss4m \
    --java-opt -Xms100m \
    --java-opt -Dmetals.client=emacs \
    org.scalameta:metals_2.13:1.3.1 -o ~/bin/metals -f
#+END_SRC

*** Anki
1. Install Anki ([[https://docs.ankiweb.net/platform/linux/installing.html][Instructions for Linux]])
2. Add [[https://git.foosoft.net/alex/anki-connect][anki-connect]] addon

*** Notdeft
**** Build Xapian Backend
1. Go to =~/$EMACS_HOME/straight/build/notdeft/xapian=
2. Run =make=
***** Fedora
Need to install =tclap= and =xapian-core-devel= packages.
* Setup
** Load local config
#+begin_src elisp
  (load (expand-file-name "local.el" user-emacs-directory))
#+end_src
** OS helpers
#+begin_src elisp
  (defun my-windows-p ()
    (eq system-type 'windows-nt))

  (defun my-mac-p ()
    (eq system-type 'darwin))
#+end_src

** Add 'lisp' dir to load path
#+begin_src elisp
  (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
#+end_src

** Windows: Add Git to path
#+begin_src elisp
  (when (my-windows-p)
    (setenv "PATH" (concat my-git-path ";" (getenv "PATH")))
    (push my-git-path exec-path))
#+end_src

** Straight :noexport_1:
https://github.com/radian-software/straight.el
*** Pre-bootstrap
#+begin_src elisp
  (setq package-enable-at-startup nil)
#+end_src

*** Bootstrap
#+begin_src elisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

*** Post-bootstrap
#+begin_src elisp
  (setq straight-use-package-by-default t)
#+end_src

** MacOS: Exec path from shell
#+begin_src elisp
(use-package exec-path-from-shell
  :when (my-mac-p)
  :config
  (exec-path-from-shell-initialize))
#+end_src

* Packages
** Emacs
#+begin_src elisp
  (use-package emacs
    :custom
    (inhibit-splash-screen t)
    (initial-major-mode 'text-mode)
    (initial-scratch-message "✅ All systems go! 🚀🪐✨")
    (disabled-command-function nil)
    (visible-bell t)
    (save-interprogram-paste-before-kill t)
    (global-auto-revert-non-file-buffers t)
    (create-lockfiles nil)
    (make-backup-files nil)
    (custom-file (expand-file-name "custom.el" user-emacs-directory))
    (require-final-newline t)
    (indent-tabs-mode nil)
    (tab-always-indent 'complete)
    (read-extended-command-predicate #'command-completion-default-include-p)
    (backward-delete-char-untabify-method 'hungry)
    (split-width-threshold 200)
    (split-height-threshold 60)
    (epa-file-encrypt-to (list my-gpg-key-id))
    (epa-pinentry-mode 'loopback)
    :config
    (set-frame-name "Main")
    (add-to-list 'default-frame-alist '(fullscreen . maximized))
    (scroll-bar-mode -1)
    (tool-bar-mode -1)
    (menu-bar-mode -1)
    (fset 'yes-or-no-p 'y-or-n-p)
    (add-hook 'prog-mode-hook 'display-line-numbers-mode)
    (global-auto-revert-mode)
    (global-subword-mode)
    (tab-bar-history-mode)
    (tab-bar-mode)
    (repeat-mode)
    :bind
    (("C-c j x" . scratch-buffer)
     ("C-x C-b" . ibuffer-other-window)
     ("M-g w" . forward-to-word)
     ("M-g W" . backward-to-word)
     ("C-M-; d" . duplicate-dwim)
     ("C-c d h" . erase-buffer)
     ("M-z" . zap-up-to-char)
     ("M-Z" . zap-to-char)
     ("C-x K" . kill-this-buffer)
     ("s-t" . tab-switch)
     ([down-mouse-2] . mouse-set-point)
     ([mouse-2] . delete-window)
     :map prog-mode-map
     ("DEL" . backward-delete-char-untabify)
     ("M-g N" . flymake-goto-next-error)
     ("M-g P" . flymake-goto-prev-error)))
#+end_src

*** My Emacs
[[file:lisp/my-emacs.org]]

#+begin_src elisp
  (use-package my-emacs
    :straight nil
    :demand
    :after emacs
    :bind
    (("C-c d w" . my/kill-forward-to-word)
     ("C-c d W" . my/kill-backward-to-word)
     ("C-c d <" . my/kill-to-beginning-of-buffer)
     ("C-c d >" . my/kill-to-end-of-buffer)
     ("C-c j h" . my/jump-home)))
#+end_src

** Modus Themes
https://protesilaos.com/emacs/modus-themes

#+begin_src elisp
  (use-package modus-themes
    :custom
    (modus-themes-italic-constructs t)
    (modus-themes-org-blocks 'gray-background)
    (modus-themes-headings '((0 . (ultrabold 1.7))
                             (1 . (ultrabold 1.7))
                             (2 . (extrabold 1.5))
                             (3 . (extrabold 1.3))
                             (4 . (extrabold 1.1))
                             (t . (extrabold))))
    (modus-themes-variable-pitch-ui t)
    :config
    (modus-themes-load-theme 'modus-vivendi))
#+end_src

** Iosevka Comfy font
https://git.sr.ht/~protesilaos/iosevka-comfy

#+begin_src elisp
  (if my-use-iosevka-comfy
      (let ((font "Iosevka Comfy Fixed"))
        (set-face-attribute 'default nil :font font :height my-iosevka-comfy-height)
        (set-frame-font font nil t))
    (if (member "Segoe UI Emoji" (font-family-list))
        (set-fontset-font t 'unicode "Segoe UI Emoji" nil 'append)))
#+end_src

** Dired
*** Dired interactive functions
**** Dired: Rename files to their modification time timestamp
#+begin_src elisp
  (defun my-dired-rename-to-timestamp ()
    (interactive)
    (let ((files (dired-get-marked-files)))
      (dolist (file files)
        (let* ((attributes (file-attributes file))
               (mod-time (file-attribute-modification-time attributes))
               (timestamp (format-time-string "%Y%m%d%H%M%S" mod-time))
               (new-name (concat timestamp (file-name-extension file t)))
               (new-path (concat (file-name-directory file) new-name)))
          (dired-rename-file file new-path nil)))))
#+end_src
*** Configure Dired
#+begin_src elisp
  (use-package dired
    :straight nil
    :custom
    (dired-dwim-target t)
    (insert-directory-program (cond ((my-windows-p) insert-directory-program)
                                    ((my-mac-p) "gls")
                                    (t "ls")))
    (dired-listing-switches (cond ((my-windows-p) dired-listing-switches)
                                  (t "-alh --group-directories-first")))
    :bind
    (("<f7>" . dired-jump)
     :map dired-mode-map
     ("o" . crux-open-with)
     ("<tab>" . dired-find-file-other-window)
     ("C-c D t" . my-dired-rename-to-timestamp)))
#+end_src

** Project
#+begin_src elisp
  (use-package project
    :config
    (add-to-list 'project-switch-commands '(project-dired "Dired" "<return>") t))
#+end_src

*** My project
[[file:lisp/my-project.org]]

#+begin_src elisp
  (use-package my-project
    :straight nil
    :after project
    :demand
    :bind
    (("C-x p P" . my-project-open-new-frame)
     ("C-x p v" . my-project-vterm)))
#+end_src

** Super Save
https://github.com/bbatsov/super-save

#+begin_src elisp
  (use-package super-save
    :custom
    (super-save-all-buffers t)
    (super-save-auto-save-when-idle t)
    (super-save-delete-trailing-whitespace 'except-current-line)
    (super-save-silent t)
    (super-save-exclude '(".sbt" "project/" ".gpg"))
    (auto-save-default nil)
    :config
    (super-save-mode))
#+end_src

** EMMS
https://www.gnu.org/software/emms/manual/#Introduction

#+begin_src elisp
  (use-package emms
    :unless (my-windows-p)
    :custom
    (emms-player-list '(emms-player-mpv))
    (emms-player-mpv-update-metadata t)
    (emms-streams-file (expand-file-name "streams.emms" user-emacs-directory))
    :config
    (emms-all)
    :bind
    (("C-c r r" . emms-streams)
     ("C-c r p" . emms-pause)
     ("C-c r s" . emms-stop)))
#+end_src

** Ace Window
https://github.com/abo-abo/ace-window

#+begin_src elisp
  (use-package ace-window
    :custom
    (aw-keys '(?a ?s ?d ?f ?g ?h ?k ?l))
    (aw-scope 'frame)
    :bind
    (("M-o" . ace-window)))
#+end_src

** Vertico
https://github.com/minad/vertico

#+begin_src elisp
  (use-package vertico
    :demand
    :config
    (vertico-mode)
    (vertico-multiform-mode)
    (add-to-list 'vertico-multiform-categories
                 '(jinx grid (vertico-grid-annotate . 20)))
    (add-to-list 'vertico-multiform-commands
                 '(consult-ripgrep buffer indexed))
    :bind
    (:map vertico-map
          ("C-;" . vertico-quick-insert)))
#+end_src

** Savehist
#+begin_src elisp
  (use-package savehist
    :config
    (savehist-mode))
#+end_src

** Orderless
https://github.com/oantolin/orderless

#+begin_src elisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** Consult
https://github.com/minad/consult

#+begin_src elisp
  (use-package consult
    :config
    ;; Don't live preview buffers to avoid triggering package loading.
    ;; See https://github.com/minad/consult#live-previews
    (consult-customize consult-buffer :preview-key "M-.")
    :bind
    (("C-x b" . consult-buffer)
     ("C-x 4 b" . consult-buffer-other-window)
     ("C-x 5 b" . consult-buffer-other-frame)
     ("C-x p b" . consult-project-buffer)
     ("M-g M-g" . consult-goto-line)
     ("M-g o" . consult-outline)
     ("M-s r" . consult-ripgrep)
     ("M-s l" . consult-line)
     ("M-s k" . consult-keep-lines)
     ("M-s f" . consult-focus-lines)))
#+end_src

*** My Consult
[[file:lisp/my-consult.org]]

#+begin_src elisp
  (use-package my-consult
    :straight nil
    :after (consult org))
#+end_src

** Corfu
https://github.com/minad/corfu

#+begin_src elisp :tangle no
  (use-package corfu
    :demand
    :custom
    (corfu-cycle t)
    (corfu-auto t)
    (corfu-auto-prefix 2)
    (corfu-quit-at-boundary 'separator)
    (corfu-quit-no-match t)
    :config
    (global-corfu-mode)
    (corfu-history-mode)
    :bind
    (:map corfu-map
          ("C-SPC" . corfu-insert-separator)
          ("C-;" . corfu-quick-insert)))
#+end_src

** Company
#+begin_src elisp
  (use-package company
    :init
    (setq company-minimum-prefix-length 2)
    (setq company-idle-delay 0.2)
    (setq company-selection-wrap-around t)
    (setq company-dabbrev-downcase nil)
    (setq company-show-numbers t)
    :config
    (global-company-mode))
#+end_src

** Smartparens
https://github.com/Fuco1/smartparens

#+begin_src elisp
  (use-package smartparens
    :hook
    (prog-mode . smartparens-mode)
    :config
    (require 'smartparens-config)
    :bind
    (:map smartparens-mode-map
          ("C-<right>" . sp-forward-slurp-sexp)
          ("C-<left>" . sp-backward-slurp-sexp)
          ("M-<right>" . sp-forward-barf-sexp)
          ("M-<left>" . sp-backward-barf-sexp)
          ("M-a" . sp-beginning-of-sexp)
          ("M-e" . sp-end-of-sexp)
          ("C-M-u" . sp-up-sexp)
          ("C-M-S-u" . sp-backward-up-sexp)
          ("C-M-d" . sp-down-sexp)
          ("C-M-S-d" . sp-backward-down-sexp)
          ("C-c p u" . sp-unwrap-sexp)
          ("C-c p (" . sp-wrap-round)
          ("C-c p [" . sp-wrap-square)
          ("C-c p {" . sp-wrap-curly)
          ("C-c p r" . sp-rewrap-sexp)))
#+end_src

** Yasnippet
https://github.com/joaotavora/yasnippet

#+begin_src elisp
  (use-package yasnippet
    :custom
    (yas-snippet-dirs (list (expand-file-name "snippets" user-emacs-directory)))
    :config
    (yas-global-mode))
#+end_src

** Avy
https://github.com/abo-abo/avy

#+begin_src elisp
  (use-package avy
    :custom
    (avy-single-candidate-jump t)
    :bind
    (("C-;" . avy-goto-char-timer)
     ("M-;" . avy-pop-mark)
     ("M-g g" . avy-goto-line)
     ("M-g G" . avy-goto-end-of-line)
     ("M-g h" . avy-org-goto-heading-timer)
     ("M-g s" . avy-goto-word-1)
     ("C-M-; c" . avy-copy-line)
     ("C-M-; C" . avy-copy-region)
     ("C-M-; m" . avy-move-line)
     ("C-M-; M" . avy-move-region)
     ("C-M-; k" . avy-kill-whole-line)
     ("C-M-; K" . avy-kill-region)
     ("C-M-; s" . avy-kill-ring-save-whole-line)
     ("C-M-; S" . avy-kill-ring-save-region)
     :map isearch-mode-map
     ("C-;" . avy-isearch)))
#+end_src

*** My Avy-Embark
[[file:lisp/my-avy-embark.org]]

#+begin_src elisp
  (use-package my-avy-embark
    :straight nil
    :after avy
    :config
    (setf (alist-get ?. avy-dispatch-alist) 'my-avy-embark)
    (setf (alist-get ?\; avy-dispatch-alist) 'my-avy-embark-dwim))
#+end_src

** Link hint
https://github.com/noctuid/link-hint.el

#+begin_src elisp
  (use-package link-hint
    :bind
    (("C-c f" . link-hint-open-link)
     ("C-c y" . link-hint-copy-link)))
#+end_src

** Crux
https://github.com/bbatsov/crux

#+begin_src elisp
  (use-package crux
    :bind
    (("C-o" . crux-smart-open-line)
     ("C-S-o" . crux-smart-open-line-above)
     ("C-^" . crux-top-join-line)
     ("C-M-; D" . crux-duplicate-and-comment-current-line-or-region)))
#+end_src

** Whole Line or Region
https://github.com/purcell/whole-line-or-region

#+begin_src elisp
  (use-package whole-line-or-region
    :demand
    :config
    (whole-line-or-region-global-mode)
    :bind
    (("M-/" . whole-line-or-region-comment-dwim)))
#+end_src

** Multiple Cursors
https://github.com/magnars/multiple-cursors.el

#+begin_src elisp
  (use-package multiple-cursors
    :bind
    (("C-+" . mc/mark-next-like-this)
     ("C-c k l" . mc/edit-lines)
     ("C-c k m" . mc/mark-all-dwim)
     ("C-S-<mouse-1>" . mc/add-cursor-on-click)
     ("C-<return>" . set-rectangular-region-anchor)))
#+end_src

** Expand Region
https://github.com/magnars/expand-region.el

#+begin_src elisp
  (use-package expand-region
    :bind
    (("C-=" . er/expand-region)))
#+end_src

** Go to Char
https://github.com/doitian/iy-go-to-char

#+begin_src elisp
  (use-package iy-go-to-char
    :bind
    (("M-g f" . iy-go-to-char)
     ("M-g F" . iy-go-to-char-backward)
     ("M-g t" . iy-go-up-to-char)
     ("M-g T" . iy-go-up-to-char-backward)
     ("M-g ;" . iy-go-to-or-up-to-continue)
     ("M-g ," . iy-go-to-or-up-to-continue-backward)))
#+end_src

** Magit
https://magit.vc/

#+begin_src elisp
  (use-package magit
    :bind
    (("C-c g" . magit-file-dispatch)))
#+end_src

** Org mode
https://orgmode.org/
*** Setup helpers
**** To run on the mode hook
#+begin_src elisp
  (defun my-org-setup ()
    (setq-local fill-column 120)
    (auto-fill-mode 1))
#+end_src
*** Helpers
**** Sort TODOs
#+begin_src elisp
  (defun my-org-sort-todos ()
    "Sort the current subtree: first 'open' items by priority, then 'done' items by priority."
    (interactive)
    (unless (org-at-heading-p)
      (error "Not at a heading"))
    (org-sort-entries nil ?p)
    (org-sort-entries nil ?o))
#+end_src
**** Jump to the last item of a subtree
#+begin_src elisp
  (defun my-org-end-of-subtree ()
    "Jump to the last item of the current subtree."
    (interactive)
    (org-end-of-subtree)
    (org-back-to-heading))
#+end_src
**** Add an update
#+begin_src elisp
  (defun my-org-add-update ()
    "Add an update entry with a timestamp to the current Org heading."
    (interactive)
    (org-end-of-subtree)
    (end-of-line)
    (newline-and-indent)
    (insert (format "# Upd. %s" (format-time-string "<%Y-%m-%d %H:%M>")))
    (newline-and-indent))
#+END_SRC
**** Insert a heading w/ a timestamp
#+begin_src elisp
  (defun my-org-insert-timestamped-heading ()
    (interactive)
    (org-insert-heading-respect-content)
    (forward-line)
    (insert "# CREATED: ")
    (org-insert-timestamp (current-time) t t)
    (insert "\n")
    (forward-line -2)
    (end-of-line))
#+end_src
*** Org files
#+begin_src elisp
  (defconst my-open-org-dir "~/org-open")

  (defconst my-local-gtd-dir (concat my-local-org-dir "/gtd"))
  (defconst my-open-gtd-dir (concat my-open-org-dir "/gtd"))

  (defun my-gtd-path (name)
    (expand-file-name (concat my-local-gtd-dir name ".org")))

  (defconst my-gtd-inbox (my-gtd-path "/inbox"))

  (defconst my-local-gtd-projects-dir (expand-file-name "projects" my-local-gtd-dir))
  (defconst my-local-gtd-areas-dir (expand-file-name "areas" my-local-gtd-dir))
  (defconst my-open-gtd-projects-dir (expand-file-name "projects" my-open-gtd-dir))
  (defconst my-open-gtd-areas-dir (expand-file-name "areas" my-open-gtd-dir))

  (defconst my-local-gtd-files `(,my-local-gtd-dir ,my-local-gtd-projects-dir ,my-local-gtd-areas-dir))
  (defconst my-open-gtd-files `(,my-open-gtd-dir ,my-open-gtd-projects-dir ,my-open-gtd-areas-dir))
  (defconst my-all-gtd-files (append my-local-gtd-files my-open-gtd-files))
#+end_src
*** Capturing
#+begin_src elisp
  (defun my-org-capture-template-path (name)
    (expand-file-name (concat "capture-templates/" name ".txt") user-emacs-directory))

  (defconst my-gtd-inbox-target `(file+headline ,my-gtd-inbox "Inbox items"))

  (defconst my-gtd-capture-templates
    `(("i" "Inbox")
      ("ii" "note" entry ,my-gtd-inbox-target (file ,(my-org-capture-template-path "gtd-note")))
      ("iI" "todo" entry ,my-gtd-inbox-target (file ,(my-org-capture-template-path "gtd-todo")))))

  (defun my-gtd-capture-note ()
    (interactive)
    (org-capture nil "ii"))

  (defun my-gtd-capture-todo ()
    (interactive)
    (org-capture nil "iI"))
#+end_src
*** Agendas
**** "Day" agenda
#+begin_src elisp
  (defun my-org-day-agenda-skip-todo-if ()
    (let ((subtree-end (save-excursion (org-end-of-subtree t)))
          (scheduled (org-get-scheduled-time (point)))
          (deadline (org-get-deadline-time (point)))
          (priority (org-get-priority (thing-at-point 'line t)))
          (tags (org-get-tags))
          (category (org-get-category)))
      (if (or scheduled
              deadline
              (string= category "OPENINBOX")
              (< priority 1000)
              (and (or (member "PROJECT" tags) (member "AREA" tags))
                   (< priority 3000)))
          subtree-end)))

  (defun my-org-day-agenda-skip-project-if ()
    (let ((subtree-end (save-excursion (org-end-of-subtree t)))
          (priority (org-get-priority (thing-at-point 'line t))))
      (if (< priority 1000)
          subtree-end)))

  (defconst my-org-day-agenda
    `("d" "Day" ((agenda "" ((org-agenda-span 1)
                             (org-agenda-skip-scheduled-if-done t)
                             (org-agenda-skip-deadline-if-done t)
                             (org-agenda-skip-timestamp-if-done t)))
                 (todo "TODO" ((org-agenda-overriding-header "Ad-hoc tasks and high-prio project tasks")
                               (org-agenda-skip-function 'my-org-day-agenda-skip-todo-if)
                               (org-agenda-files ',my-local-gtd-files)))
                 (tags "+PROJECT" ((org-agenda-overriding-header "Projects")
                                   (org-tags-match-list-sublevels nil)
                                   (org-agenda-sorting-strategy '(priority-down))
                                   (org-agenda-skip-function 'my-org-day-agenda-skip-project-if)
                                   (org-agenda-files '(,my-local-gtd-projects-dir))))
                 (todo "TODO" ((org-agenda-overriding-header "Open ad-hoc tasks and high-prio project tasks")
                               (org-agenda-skip-function 'my-org-day-agenda-skip-todo-if)
                               (org-agenda-files ',my-open-gtd-files)))
                 (tags "+PROJECT" ((org-agenda-overriding-header "Open projects")
                                   (org-tags-match-list-sublevels nil)
                                   (org-agenda-sorting-strategy '(priority-down))
                                   (org-agenda-skip-function 'my-org-day-agenda-skip-project-if)
                                   (org-agenda-files '(,my-open-gtd-projects-dir)))))))
#+end_src
*** Configure
#+begin_src elisp
  (use-package org
    :custom
    (org-startup-indented t)
    (org-startup-with-inline-images t)
    (org-confirm-babel-evaluate nil)
    (org-use-sub-superscripts '{})
    (org-src-window-setup 'split-window-below)
    (org-fold-catch-invisible-edits 'show-and-error)
    (org-special-ctrl-a/e t)
    (org-hide-emphasis-markers t)
    (org-pretty-entities t)
    (org-use-speed-commands t)
    (org-attach-id-dir (concat my-local-org-dir "/attachments/"))
    (org-attach-use-inheritance nil)
    (org-startup-folded 'showall)
    (org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
    (org-log-done 'time)
    (org-capture-templates my-gtd-capture-templates)
    (org-agenda-files `(,my-local-gtd-dir
                        ,(expand-file-name "projects" my-local-gtd-dir)
                        ,(expand-file-name "areas" my-local-gtd-dir)
                        ,my-open-gtd-dir
                        ,(expand-file-name "projects" my-open-gtd-dir)
                        ,(expand-file-name "areas" my-open-gtd-dir)))
    (org-refile-targets '((org-agenda-files :level . 2)))
    (org-priority-lowest 69)
    (org-priority-default 68)
    (org-agenda-custom-commands `(,my-org-day-agenda))
    (org-habit-graph-column 80)
    :config
    (require 'org-attach)
    (require 'org-id)
    (require 'org-habit)
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((shell . t)))
    (add-to-list 'org-modules 'org-id)
    (add-hook 'org-mode-hook 'my-org-setup)
    :bind
    (("C-c c" . org-capture)
     ("C-c l" . org-store-link)
     ("C-c a" . org-agenda)
     ("C-c S" . my-org-sort-todos)
     ("M-g e" . my-org-end-of-subtree)
     ("C-c i" . my-gtd-capture-note)
     ("C-c I" . my-gtd-capture-todo)
     ("C-c o u" . my-org-add-update)
     ("C-c o l" . my-org-insert-timestamped-heading)
     :map org-mode-map
     ("C-c P i" . org-id-get-create)))
#+end_src

*** Org Modern
https://github.com/minad/org-modern
**** Setup helpers
***** Make checked checkboxes green
Org Modern makes checkboxes very small and it's hard to distinguish checked from unchecked. This makes checked ones
green to help with that.

#+begin_src elisp
  (defface my-org-checked-checkbox-face
    '((t (:inherit org-done)))
    "Face for a checked Org mode checkbox.")

  (defun my-org-set-checked-checkbox-face ()
    (font-lock-add-keywords
     'org-mode
     `(("^[ \t]*\\(?:[-+*]\\|[0-9]+[).]\\)[ \t]+\\(\\(?:\\[@\\(?:start:\\)?[0-9]+\\][ \t]*\\)?\\[\\(?:X\\|\\([0-9]+\\)/\\2\\)\\][^\n]*\n\\)" 1 'my-org-checked-checkbox-face prepend))
     'append))
#+end_src
**** Configure
#+begin_src elisp
  (use-package org-modern
    :after org
    :custom
    (org-auto-align-tags nil)
    (org-tags-column 0)
    (org-agenda-tags-column 0)
    (org-modern-priority-faces '((?A :background "IndianRed" :foreground "white")
                                 (?B :background "Goldenrod" :foreground "white")
                                 (?C :background "DarkOliveGreen" :foreground "white")
                                 (?D :background "SteelBlue" :foreground "white")
                                 (?E :background "DarkOrchid" :foreground "white")))
    :custom-face
    (org-modern-tag ((t (:foreground "white" :background "#9575cd" :slant italic))))
    (org-checkbox ((t (:height 1.3))))
    :config
    (global-org-modern-mode)
    (my-org-set-checked-checkbox-face))
#+end_src
*** Auto-tangle
https://github.com/yilkalargaw/org-auto-tangle

#+begin_src elisp
  (use-package org-auto-tangle
    :hook (org-mode . org-auto-tangle-mode))
#+end_src

*** TOC
https://github.com/snosov1/toc-org

#+begin_src elisp
  (use-package toc-org
    :hook (org-mode . toc-org-mode))
#+end_src

*** Restclient
https://github.com/alf/ob-restclient.el

#+begin_src elisp
  (use-package ob-restclient
    :after org)
#+end_src

*** ox-slack
https://github.com/titaniumbones/ox-slack

#+begin_src elisp
  (use-package ox-slack
    :after org)
#+end_src

** Org super links
https://github.com/toshism/org-super-links

#+begin_src elisp
  (use-package org-super-links
    :straight (org-super-links :type git :host github :repo "toshism/org-super-links" :branch "develop")
    :bind (("C-c s s" . org-super-links-link)
           ("C-c s l" . org-super-links-store-link)
           ("C-c s C-l" . org-super-links-insert-link)))
#+end_src

** GPTel
https://github.com/karthink/gptel

#+begin_src elisp
  (use-package gptel
    :custom
    (gptel-model "gpt-4o")
    (gptel-default-mode 'org-mode)
    :config
    (add-hook 'gptel-mode-hook 'toggle-truncate-lines)
    (require 'my-gptel)
    :bind
    (("C-c SPC" . gptel)
     :map gptel-mode-map
     ("C-c k" . gptel-abort)))
#+end_src

*** My GPTel
[[file:lisp/my-gptel.org]]

#+begin_src elisp
  (use-package my-gptel
    :straight nil
    :mode ("\\.gpt\\'" . my-gptel-mode)
    :bind
    (:map gptel-mode-map
          ("C-c d h" . my-gptel-clear-buffer)
          ("C-c C-c" . my-gptel-send)))
#+end_src

** Ledger
https://github.com/ledger/ledger-mode

#+begin_src elisp
  (use-package ledger-mode
    :unless (my-windows-p)
    :custom
    (ledger-default-date-format "%Y-%m-%d"))
#+end_src

*** My Ledger
[[file:lisp/my-ledger.org]]

#+begin_src elisp
  (use-package my-ledger
    :straight nil
    :after ledger-mode)
#+end_src

** Vterm
https://github.com/vterm/vterm

#+begin_src elisp
  (use-package vterm
    :unless (my-windows-p)
    :custom
    (vterm-module-cmake-args "-DUSE_SYSTEM_LIBVTERM=no")
    (vterm-shell my-fish-path)
    (vterm-max-scrollback 50000)
    (vterm-clear-scrollback-when-clearing t)
    :bind
    (("C-x v" . vterm)
     ("C-x 4 v" . vterm-other-window)))
#+end_src

** Shell
#+begin_src elisp
  (use-package shell
    :custom
    (shell-kill-buffer-on-exit t))
#+end_src

** Copilot
https://github.com/zerolfx/copilot.el

#+begin_src elisp
  (use-package copilot
    :unless (my-windows-p)
    :straight (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el"))
    :custom
    (copilot-idle-delay 0.3)
    :custom-face (copilot-overlay-face ((t (:foreground "#708090" :slant italic))))
    :config
    (add-to-list 'warning-suppress-log-types '(copilot copilot-no-mode-indent))
    :hook (prog-mode . copilot-mode))
#+end_src

*** My Copilot
[[file:lisp/my-copilot.org]]

#+begin_src elisp
  (use-package my-copilot
    :straight nil
    :after copilot)
#+end_src

** Jinx
https://github.com/minad/jinx

#+begin_src elisp
  (use-package jinx
    :unless (my-windows-p)
    :custom (jinx-languages "en_US de_DE ru")
    :hook (emacs-startup . global-jinx-mode)
    :bind
    (("M-$" . jinx-correct)
     ("C-M-$" . jinx-languages)))
#+end_src

** Ripgrep
https://github.com/dajva/rg.el

#+begin_src elisp
  (use-package rg
    :unless (my-windows-p)
    :bind
    (("M-s R" . rg-project)))
#+end_src

** Tree Sitter
#+begin_src elisp
  (use-package tree-sitter
    :unless (my-windows-p)
    :custom
    (treesit-font-lock-level 4))
#+end_src

** Eglot
#+begin_src elisp :tangle no
  (use-package eglot
    :unless (my-windows-p)
    :hook (scala-ts-mode . eglot-ensure)
    :config
    (add-to-list 'eglot-server-programs '((scala-ts-mode) . ("metals")))
    :bind
    (:map eglot-mode-map
          ("C-c e a" . eglot-code-actions)
          ("C-c e i" . eglot-code-action-organize-imports)
          ("C-c e f" . eglot-format-buffer)
          ("C-c e r" . eglot-rename)
          ([M-down-mouse-1] . mouse-set-point)
          ([M-mouse-1] . xref-find-definitions)
          ([M-mouse-3] . xref-go-back)))
#+end_src

** LSP
#+begin_src elisp
  (use-package lsp-mode
    :custom
    (lsp-keymap-prefix "<f5>")
    (lsp-pylsp-plugins-black-enabled t)
    :hook
    (scala-ts-mode . lsp)
    (python-mode . lsp)
    :commands lsp
    :bind
    (:map lsp-mode-map
          ([M-down-mouse-1] . mouse-set-point)
          ([M-mouse-1] . lsp-find-definition)
          ([M-mouse-3] . xref-go-back)
          ("<f5> I" . lsp-metals-build-import)))

  (use-package lsp-metals)

  (use-package lsp-ui :commands lsp-ui-mode)

  (setq lsp-completion-provider :none)

  (defun corfu-lsp-setup ()
    (setq-local completion-styles '(orderless)
                completion-category-defaults nil))

  (add-hook 'lsp-mode-hook #'corfu-lsp-setup)
#+end_src

** Consult-LSP
#+begin_src elisp
  (use-package consult-lsp
    :bind
    (:map lsp-mode-map
          ("<f5> d" . consult-lsp-diagnostics)
          ("<f5> s" . consult-lsp-file-symbols)
          ("<f5> S" . consult-lsp-symbols)))
#+end_src

** Flycheck
#+begin_src elisp
  (use-package flycheck
    :init
    (setq flycheck-global-modes '(not org-mode))
    :config
    (global-flycheck-mode))
#+end_src

** Scala TS mode
https://github.com/KaranAhlawat/scala-ts-mode

#+begin_src elisp
  (use-package scala-ts-mode
    :unless (my-windows-p)
    :interpreter "scala")
#+end_src

** Jarchive
#+begin_src elisp
  (use-package jarchive
    :unless (my-windows-p)
    :after eglot
    :config
    (jarchive-setup))
#+end_src

** Kubel
https://github.com/abrochard/kubel

#+begin_src elisp
  (use-package kubel
    :unless (my-windows-p)
    :config
    (with-eval-after-load 'vterm
      (add-to-list 'vterm-tramp-shells '("kubectl" "/bin/bash")))
    :bind
    (("C-c K" . kubel)
     :map kubel-mode-map
     ("n" . next-line)
     ("p" . previous-line)
     ("N" . kubel-set-namespace)
     ("v" . kubel-exec-vterm-pod)
     ("D" . kubel-exec-pod)
     ("P" . kubel-port-forward-pod)))
#+end_src

** Markdown
#+begin_src elisp
  (use-package markdown-mode
    :interpreter "markdown")
#+end_src

** Anki editor
https://github.com/louietan/anki-editor

#+begin_src elisp
  (define-derived-mode anki-mode org-mode "Anki")

  (add-to-list 'auto-mode-alist '("\\.anki\\'" . anki-mode))

  (use-package anki-editor
    :unless (my-windows-p)
    :hook (anki-mode . anki-editor-mode)
    :bind
    (:map anki-mode-map
          ("C-<return>" . anki-editor-insert-note)
          ("C-c p p" . anki-editor-push-notes)
          ("C-c p r" . anki-editor-retry-failure-notes)))
#+end_src

** PlantUML
#+begin_src elisp
  (use-package plantuml-mode)
#+end_src

** Clojure mode
#+begin_src elisp
  (use-package clojure-mode)
#+end_src

** CIDER
#+begin_src elisp
  (use-package cider)
#+end_src

** Clerk
#+begin_src elisp
  (defun clerk-show ()
    (interactive)
    (when-let
        ((filename
          (buffer-file-name)))
      (save-buffer)
      (cider-interactive-eval
       (concat "(nextjournal.clerk/show! \"" filename "\")"))))

  (define-key clojure-mode-map (kbd "<M-return>") 'clerk-show)
#+end_src

** OpenAI tools
#+begin_src elisp
    (use-package my-openai-tools
      :straight nil)
#+end_src

** Terraform
#+begin_src elisp
  (use-package terraform-mode)
#+end_src

** GraphQL
#+begin_src elisp
  (use-package graphql-mode)
#+END_SRC

** decide-mode
#+begin_src elisp
  (use-package decide)
#+end_src

** Embark
#+begin_src elisp
  (use-package embark
    :bind
    (("C-." . embark-act)
     ("M-." . embark-dwim)))
#+end_src

** Emabrk-Consult
#+begin_src elisp
  (use-package embark-consult
    :after (embark consult))
#+end_src

** Org-roam
https://www.orgroam.com/

#+begin_src elisp :tangle no
  (defconst my-roam-dailies-file-template
    (let ((base "%<%Y-%m-%d>.org"))
      (if my-roam-encrypt-dailies? (concat base ".gpg") base)))

  (use-package org-roam
    :custom
    (org-roam-directory "~/roam")
    (org-roam-database-connector 'sqlite-builtin)
    (org-roam-db-gc-threshold most-positive-fixnum)
    :config
    (add-to-list 'display-buffer-alist
                 '("\\*org-roam\\*"
                   (display-buffer-in-direction)
                   (direction . right)
                   (window-width . 0.33)
                   (window-height . fit-window-to-buffer)))
    (org-roam-db-autosync-mode)
    (require 'org-roam-dailies)
    (setq org-roam-dailies-capture-templates `(("d" "default" entry "* %?" :target
                                                (file+head ,my-roam-dailies-file-template "#+title: %<%Y-%m-%d>
  "))))
    :bind
    (("C-c n f" . org-roam-node-find)
     ("C-c n i" . org-roam-node-insert)
     ("C-c n d t" . org-roam-dailies-capture-today)
     ("C-c n d y" . org-roam-dailies-capture-yesterday)
     ("C-c n d T" . org-roam-dailies-goto-today)
     ("C-c n d Y" . org-roam-dailies-goto-yesterday)
     :map org-mode-map
     ("C-c n t a" . org-roam-tag-add)
     ("C-c n t r" . org-roam-tag-remove)))
#+end_src

** Org-roam UI
https://github.com/org-roam/org-roam-ui

#+begin_src elisp :tangle no
  (use-package org-roam-ui)
#+end_src

** Notdeft
https://github.com/hasu/notdeft

#+begin_src elisp
  (use-package notdeft
    :straight (notdeft :type git :host github :repo "hasu/notdeft" :files ("*.el" "xapian"))
    :custom
    (notdeft-directory "~/roam")
    (notdeft-directories '("~/roam"))
    (notdeft-xapian-program (expand-file-name "straight/build/notdeft/xapian/notdeft-xapian" user-emacs-directory))
    :config
    (notdeft-install)
    :bind
    (("C-c n n" . notdeft)))
#+end_src

** dash
https://github.com/magnars/dash.el

#+begin_src elisp
  (use-package dash)
#+end_src

** envrc
#+begin_src elisp
  (use-package envrc
    :hook (after-init . envrc-global-mode))
#+end_src

** emacs-pet
#+begin_src elisp
  (use-package pet
    :config
    (add-hook 'python-base-mode-hook 'pet-mode -10)
    (require 'envrc)
    (add-hook 'change-major-mode-after-body-hook 'envrc-mode))
#+end_src

** just
https://github.com/leon-barrett/just-mode.el

#+begin_src elisp
  (use-package just-mode)
#+end_src

* Local variables :noexport:
# Local Variables:
# jinx-local-words: "Avy Dired Eglot GPTel Iosevka Jarchive Kubel Magit Modus Orderless Restclient Ripgrep Savehist Smartparens Vertico Vterm Yasnippet mpv vterm"
# End:
